const root = "/Assets/redesign";
export const assets = {
  logo: `${root}/Brand/Taprank logo Transparent.png`,
  whiteLogo: `${root}/Brand/White Taprank logo Transparent Background.png`,
  google: `${root}/Stands/Google review stand New design.png`,
  googleClassic: `${root}/Stands/Google review stand.png`,
  instagram: `${root}/Stands/Instagram new design.png`,
  tripadvisor: `${root}/Stands/Trip advisor new design.png`,
  custom: `${root}/Stands/Custom stands Transparent.png`,
  restaurantPage: `${root}/Hosted pages/restaurant-demo-homepage.jpg`,
  spacePage: `${root}/Hosted pages/Spacejump web design showcase on phone.png`,
  // The supplied Restaurant file also depicts Space Jump; do not mislabel it.
  videoPoster: `${root}/Video/taprank-demo-poster.jpg`,
  video: `${root}/Video/taprank-demo-web.mp4`,
  platforms: { google: `${root}/Platform logos/Google.PNG`, instagram: `${root}/Platform logos/Instagram.PNG`, tripadvisor: `${root}/Platform logos/Tripadvisor.PNG` },
};
export const googleDesigns = [
  { id: "new", name: "Current design", image: assets.google, soldOut: false },
  { id: "classic", name: "Classic design", image: assets.googleClassic, soldOut: true },
];
export const variants = [
  { id: "google", name: "Google Review", price: "64.99", accent: "#1654ed", image: assets.google, route: "/google-review-stand", description: "Prioritise getting more Google reviews. Make leaving a review the obvious first step, with your other useful business links on the same TapRank page.", caption: "A little prompt. A lasting impression." },
  { id: "instagram", name: "Instagram", price: "64.99", accent: "#af2875", image: assets.instagram, route: "/instagram-stand", description: "Prioritise growing your Instagram following. Put Instagram front and centre, with reviews, bookings and more on your TapRank page.", caption: "From in-person moments to online connections." },
  { id: "tripadvisor", name: "Tripadvisor", price: "64.99", accent: "#087f63", image: assets.tripadvisor, route: "/tripadvisor-stand", description: "Prioritise Tripadvisor reviews. Give guests a simple first step, alongside your menu, directions and other useful links.", caption: "Great experiences deserve to be shared." },
  { id: "custom", name: "Custom Logo + Branding", price: "84.99", accent: "#19315a", image: assets.custom, route: "/custom-taprank", description: "Put your business logo and branding first. Your tailored stand opens a custom-branded TapRank page with the links that matter to your business.", caption: "Your brand, on both sides of the tap." },
];

export const productLandingContent = Object.freeze({
  google: Object.freeze({
    id: "google",
    route: "/google-review-stand",
    name: "Google Review TapRank",
    shortName: "Google Review",
    price: "64.99",
    accent: "#1755ef",
    image: assets.google,
    imageAlt: "Current design Google Review TapRank NFC and QR acrylic stand",
    eyebrow: "Google Review TapRank · Current design",
    headline: "Get more Google reviews while customers are still in your business.",
    lead: "Customers tap or scan. Your TapRank page opens instantly, with Google Reviews as the clear first action.",
    cta: "Get my Google Review TapRank — £64.99",
    outcome: "Google Reviews",
    seoTitle: "Google Review Stand | NFC + QR TapRank — £64.99",
    seoDescription: "Help happy customers reach your Google review experience while they are still in your business. NFC + QR TapRank stand, hosted page, free UK delivery and no subscription.",
  }),
  instagram: Object.freeze({
    id: "instagram",
    route: "/instagram-stand",
    name: "Instagram TapRank",
    shortName: "Instagram",
    price: "64.99",
    accent: "#af2875",
    image: assets.instagram,
    imageAlt: "Instagram TapRank NFC and QR acrylic stand",
    eyebrow: "Instagram TapRank",
    headline: "Turn in-person customers into Instagram followers.",
    lead: "Customers tap or scan. Your TapRank page opens with Instagram as the clear first action, alongside your other useful links.",
    cta: "Get my Instagram TapRank — £64.99",
    outcome: "Instagram",
    seoTitle: "Instagram NFC Stand | TapRank — £64.99",
    seoDescription: "Help customers find your Instagram from an NFC + QR TapRank stand. Includes a hosted business page, setup, free UK delivery and no subscription.",
  }),
  tripadvisor: Object.freeze({
    id: "tripadvisor",
    route: "/tripadvisor-stand",
    name: "Tripadvisor TapRank",
    shortName: "Tripadvisor",
    price: "64.99",
    accent: "#087f63",
    image: assets.tripadvisor,
    imageAlt: "Tripadvisor TapRank NFC and QR acrylic stand",
    eyebrow: "Tripadvisor TapRank",
    headline: "Make sharing a great visit on Tripadvisor the easy next step.",
    lead: "Customers tap or scan. Your TapRank page opens with Tripadvisor as the clear first action, alongside your other useful links.",
    cta: "Get my Tripadvisor TapRank — £64.99",
    outcome: "Tripadvisor",
    seoTitle: "Tripadvisor Review Stand | TapRank — £64.99",
    seoDescription: "Give guests an easy route to Tripadvisor from an NFC + QR TapRank stand. Includes a hosted business page, setup, free UK delivery and no subscription.",
  }),
  custom: Object.freeze({
    id: "custom",
    route: "/custom-taprank",
    name: "Custom TapRank",
    shortName: "Custom Branding + Logo",
    price: "84.99",
    accent: "#19315a",
    image: assets.custom,
    imageAlt: "Custom logo and branding TapRank stand examples",
    eyebrow: "Custom Logo + Branding",
    headline: "A TapRank stand designed to feel like your business.",
    lead: "Your logo and colours on a tailored stand, connected to a custom-branded TapRank page with your most important business actions.",
    cta: "Get my Custom TapRank — £84.99",
    outcome: "your chosen primary action",
    seoTitle: "Custom Branded NFC + QR Stand | TapRank — £84.99",
    seoDescription: "A custom-branded TapRank NFC + QR stand with your logo, colours and hosted business page. One-off payment, free UK delivery and no subscription.",
  }),
});

// Supplied, approved proof content. Keep this anonymous until TapRank has
// permission to add the customer's identity, logo, screenshots or exact counts.
export const customerProof = Object.freeze({
  metricPrefix: "More than",
  metric: "4×",
  timeframe: "the reviews in approximately two months",
  summary: "One TapRank business grew its review count by more than four times within approximately two months of using TapRank.",
  disclaimer: "Individual results vary. This is not a guarantee.",
  quoteLead: "The whole process was quick, easy and very professional.",
  quoteBody: "The quality of the stand is fantastic, and everything works perfectly. I highly recommend TapRank to any business looking for an easy way to collect Google reviews and grow their online presence.",
  reviewer: "Iryna S.",
  sourceLabel: "5-star customer review on Trustpilot · July 2026",
  sourceUrl: "https://uk.trustpilot.com/reviews/6a5bcd66e47e7599cd68a220",
});
export const actions = [
  { id: "review", label: "Review", title: "Make their next review an easy one.", copy: "Bring Google Reviews or Tripadvisor into the moment, while the experience is still fresh.", image: `${root}/Actions/Google review.jpg`, width: 1173, height: 282, alt: "Example Google review action on a TapRank page" },
  { id: "follow", label: "Follow", title: "Keep the connection going.", copy: "Help customers find your Instagram without typing, searching or guessing your handle." },
  { id: "book", label: "Book", title: "Give the next visit a head start.", copy: "Connect customers to your booking page or enquiry link, right from your TapRank page.", image: `${root}/Actions/Booking Enquiry.jpg`, width: 575, height: 252, alt: "Booking enquiry action example" },
  { id: "browse", label: "Browse", title: "Your menu. Right in their hands.", copy: "A menu, website or more about your business. Give customers the information they came for.", image: `${root}/Actions/Menu.jpg`, width: 585, height: 239, alt: "Example menu action" },
  { id: "call", label: "Call", title: "Make getting in touch simple.", copy: "Keep your phone number one clear action away, alongside the other ways to connect with you.", image: `${root}/Actions/Call resturant.jpg`, width: 565, height: 231, alt: "Example restaurant phone action" },
  { id: "find", label: "Find us", title: "Help them find their way back.", copy: "Put directions, opening hours and location details together on your business page.", image: `${root}/Actions/Directions .jpg`, width: 577, height: 241, extraImage: `${root}/Actions/More info : location.jpg`, alt: "Directions action example" },
];
export const faqs = [
  ["How does TapRank work?", "A customer taps a compatible phone on the NFC area or scans the QR code. Both open your TapRank-hosted business page, where they can choose reviews, Instagram, Tripadvisor, your menu, bookings and other links you provide."],
  ["Do customers need an app?", "No TapRank app or download is needed. Your page opens in their phone’s browser. Some destinations may ask customers to sign in, for example to leave a review."],
  ["Does it work with iPhone and Android?", "NFC works with most modern iPhone and Android phones with NFC enabled. The QR code provides an alternative using the phone’s camera. An internet connection is needed to open your page."],
  ["What happens after I order?", "On a product page, configure your main action and optional business links before checkout. TapRank reviews the supplied destinations, prepares your hosted page, generates and configures the QR code, and configures the NFC before dispatch. Your A7 acrylic stand arrives ready to use."],
  ["What’s the difference between Standard and Custom?", "Standard is £64.99: choose Google Review, Instagram or Tripadvisor, with the standard TapRank-hosted page design. Custom Logo + Branding is £84.99 and includes your logo, colours and tailored stand design, plus a custom-branded hosted page."],
  ["Can I change the links later?", "Yes. Contact TapRank to arrange a link update. Your stand points to a permanent TapRank page, so changing destinations does not require reprinting the QR code or reprogramming the NFC. Updates are managed by TapRank."],
  ["Is there a monthly subscription?", "No monthly subscription is required. Your one-off purchase includes the stand, setup and TapRank-hosted business page."],
  ["How quickly is it dispatched?", "We dispatch within 48 hours of receiving your business details, with free UK delivery. Dispatch is when your order leaves us; it is not a promise of delivery within 48 hours."],
  ["What warranty is included?", "Every TapRank includes a 1-year replacement warranty. Contact TapRank with your order details if you need help with a replacement."],
  ["Can I order multiple stands?", "Yes. Contact TapRank with your quantity, locations and branding needs for a multiple-stand enquiry."],
];
